[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
solc-version = "0.8.22" # hardhat.config.ts
optimizer = true # hardhat.config.ts
optimizer-runs = 2000 # Should match with hardhat.config.ts
cache_path = 'cache_forge'
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "@src/=src/",
]
